server:
  port: 8888
  
spring:
  application:
    name: userconsul8888
  cloud:
    consul:
      port: 8500
      discovery:
        register-health-check: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

feign:
  circuitbreaker:
    enabled: true
    
        
name: zexwsml6666666666
